INSERT INTO product (id, name, description, category_id, price, stock, created_at)
VALUES
    (1, 'Wireless Mouse', 'A reliable wireless mouse with ergonomic design.', 1, 25.99, 100, NOW()),
    (2, 'Mechanical Keyboard', 'A durable mechanical keyboard with RGB lighting.', 1, 85.50, 50, NOW()),
    (3, 'Yoga Mat', 'A high-quality yoga mat for comfort and durability.', 2, 19.99, 200, NOW()),
    (4, 'Protein Powder', 'Premium whey protein for muscle building.', 2, 35.75, 75, NOW()),
    (5, 'Fiction Book', 'A best-selling fiction novel.', 3, 10.99, 120, NOW()),
    (6, 'Cookbook', 'A popular cookbook with easy recipes.', 3, 14.99, 60, NOW()),
    (7, 'Gaming Laptop', 'A powerful gaming laptop with high performance.', 1, 1299.99, 10, NOW()),
    (8, 'Dumbbells Set', 'A set of adjustable dumbbells for home workouts.', 2, 50.00, 40, NOW()),
    (9, 'Smartphone', 'A sleek smartphone with cutting-edge features.', 1, 699.00, 70, NOW()),
    (10, 'Bluetooth Speaker', 'A portable Bluetooth speaker with excellent sound quality.', 1, 49.99, 85, NOW()),
    (11, 'Running Shoes', 'Comfortable running shoes for daily exercise.', 2, 59.99, 90, NOW()),
    (12, 'Resistance Bands', 'Durable resistance bands for strength training.', 2, 15.99, 150, NOW()),
    (13, 'Mystery Novel', 'An intriguing mystery novel to keep you hooked.', 3, 12.99, 110, NOW()),
    (14, 'History Book', 'An engaging book on world history.', 3, 20.99, 50, NOW()),
    (15, 'Tablet', 'A lightweight tablet with a powerful processor.', 1, 399.99, 30, NOW()),
    (16, 'Smartwatch', 'A stylish smartwatch with health tracking features.', 1, 199.99, 40, NOW()),
    (17, 'Cycling Helmet', 'A safe and comfortable helmet for cyclists.', 2, 45.00, 60, NOW()),
    (18, 'Yoga Block', 'A sturdy yoga block for improved flexibility.', 2, 9.99, 140, NOW()),
    (19, 'Romance Novel', 'A heartwarming romance novel.', 3, 9.99, 130, NOW()),
    (20, 'Science Fiction Novel', 'A thrilling science fiction novel.', 3, 15.99, 100, NOW()),
    (21, '4K TV', 'A stunning 4K Ultra HD television.', 1, 799.99, 25, NOW()),
    (22, 'Electric Toothbrush', 'An electric toothbrush with multiple modes.', 1, 39.99, 80, NOW()),
    (23, 'Adjustable Bench', 'A sturdy adjustable bench for workouts.', 2, 120.00, 30, NOW()),
    (24, 'Treadmill', 'A compact treadmill for indoor running.', 2, 599.99, 15, NOW()),
    (25, 'Self-Help Book', 'A motivational self-help book.', 3, 11.99, 90, NOW()),
    (26, 'Cookware Set', 'A high-quality non-stick cookware set.', 4, 149.99, 20, NOW()),
    (27, 'Gaming Headset', 'A headset with surround sound for gamers.', 1, 79.99, 50, NOW()),
    (28, 'Power Bank', 'A high-capacity power bank for mobile devices.', 1, 29.99, 75, NOW()),
    (29, 'Kettlebell', 'A cast iron kettlebell for strength training.', 2, 35.00, 60, NOW()),
    (30, 'Pull-Up Bar', 'A door-frame pull-up bar for home workouts.', 2, 25.00, 50, NOW()),
    (31, 'Thermos', 'A vacuum insulated thermos for hot and cold drinks.', 4, 19.99, 100, NOW()),
    (32, 'Gaming Chair', 'An ergonomic chair designed for gamers.', 1, 199.99, 20, NOW()),
    (33, 'Puzzle Book', 'A book filled with engaging puzzles and games.', 3, 7.99, 120, NOW()),
    (34, 'Fantasy Novel', 'An epic fantasy novel.', 3, 17.99, 70, NOW()),
    (35, 'Blender', 'A powerful blender for smoothies and soups.', 4, 89.99, 25, NOW())
    (36, 'Camping Tent', 'A waterproof camping tent for 2 people.', 5, 99.99, 30, NOW()),
    (37, 'Trekking Pole', 'Durable trekking poles for hiking enthusiasts.', 5, 45.00, 35, NOW()),
    (38, 'Electric Kettle', 'A fast-boiling electric kettle.', 4, 29.99, 40, NOW()),
    (39, 'Frying Pan', 'A non-stick frying pan with a sturdy handle.', 4, 19.99, 60, NOW()),
    (40, 'Novel Collection', 'A collection of popular novels.', 3, 24.99, 50, NOW()),
    (41, 'Suspense Novel', 'An edge-of-your-seat suspense novel.', 3, 12.99, 100, NOW()),
    (42, 'Treadmill', 'A compact treadmill for indoor running.', 2, 599.99, 15, NOW()),
    (43, 'Jump Rope', 'A high-speed jump rope for cardio workouts.', 2, 9.99, 150, NOW()),
    (44, 'Gaming Console', 'A next-gen gaming console.', 1, 499.99, 25, NOW()),
    (45, 'Noise-Canceling Headphones', 'Premium headphones with noise-canceling feature.', 1, 149.99, 40, NOW()),
    (46, 'Action Camera', 'A waterproof action camera for adventures.', 1, 199.99, 20, NOW()),
    (47, 'Camping Chair', 'A foldable camping chair with a cup holder.', 5, 39.99, 50, NOW()),
    (48, 'Grill Set', 'A complete BBQ grill set.', 4, 89.99, 25, NOW()),
    (49, 'Blender', 'A high-speed blender for smoothies.', 4, 79.99, 35, NOW()),
    (50, 'Meditation Cushion', 'A comfortable cushion for meditation.', 2, 29.99, 80, NOW()),
    (51, 'Laptop Stand', 'An adjustable laptop stand for better posture.', 1, 45.99, 70, NOW()),
    (52, 'VR Headset', 'A virtual reality headset for immersive gaming.', 1, 399.99, 15, NOW()),
    (53, 'Water Bottle', 'A durable and reusable water bottle.', 4, 14.99, 120, NOW()),
    (54, 'Cooking Knife Set', 'A professional-grade knife set for chefs.', 4, 99.99, 20, NOW()),
    (55, 'Cookbook', 'A detailed cookbook with gourmet recipes.', 3, 14.99, 60, NOW()),
    (56, 'Yoga Blocks', 'Two sturdy yoga blocks for better stretches.', 2, 19.99, 90, NOW()),
    (57, 'Wireless Charger', 'A fast wireless charger for smartphones.', 1, 29.99, 80, NOW()),
    (58, 'Gaming Keyboard', 'A mechanical gaming keyboard with backlight.', 1, 89.99, 50, NOW()),
    (59, 'Outdoor Jacket', 'A waterproof jacket for hiking.', 5, 129.99, 25, NOW()),
    (60, 'Hiking Boots', 'Durable boots for mountain hiking.', 5, 139.99, 20, NOW()),
    (61, 'Running Belt', 'A lightweight running belt with pockets.', 2, 19.99, 100, NOW()),
    (62, 'Tablet Stand', 'An adjustable stand for tablets.', 1, 19.99, 70, NOW()),
    (63, 'Cycling Gloves', 'Comfortable gloves for long cycling rides.', 2, 24.99, 80, NOW()),
    (64, 'Camping Lantern', 'A rechargeable camping lantern with high brightness.', 5, 34.99, 45, NOW()),
    (65, 'Smoothie Recipe Book', 'A collection of healthy smoothie recipes.', 3, 9.99, 60, NOW()),
    (66, 'Trail Backpack', 'A spacious backpack for long trails.', 5, 49.99, 30, NOW()),
    (67, 'Popcorn Maker', 'A compact popcorn maker for movie nights.', 4, 24.99, 35, NOW()),
    (68, 'Fitness Tracker', 'A smart fitness tracker for monitoring activity.', 2, 99.99, 30, NOW()),
    (69, 'Streaming Webcam', 'A high-quality webcam for streaming.', 1, 59.99, 50, NOW()),
    (70, 'Electric Griddle', 'A non-stick electric griddle for quick meals.', 4, 69.99, 20, NOW()),
    (71, 'E-Reader', 'A lightweight e-reader for books on the go.', 3, 129.99, 25, NOW()),
    (72, 'Hiking Socks', 'Moisture-wicking socks for hiking.', 5, 14.99, 100, NOW()),
    (73, 'Hand Mixer', 'A lightweight hand mixer for baking.', 4, 29.99, 45, NOW()),
    (74, 'Yoga Mat Bag', 'A spacious bag for yoga mats and accessories.', 2, 25.99, 60, NOW()),
    (75, 'Power Drill', 'A cordless power drill for home projects.', 1, 89.99, 20, NOW()),
    (76, 'Portable Stove', 'A compact stove for outdoor cooking.', 5, 49.99, 35, NOW()),
    (77, 'Resistance Bands Set', 'A set of resistance bands for various exercises.', 2, 29.99, 80, NOW()),
    (78, 'Skillet', 'A heavy-duty skillet for even cooking.', 4, 39.99, 30, NOW()),
    (79, 'Smart Home Hub', 'A hub to control all smart home devices.', 1, 149.99, 15, NOW()),
    (80, 'Hiking Tent', 'A lightweight tent for solo hikers.', 5, 119.99, 10, NOW()),
    (81, 'Board Game', 'A fun and interactive board game.', 3, 29.99, 50, NOW()),
    (82, 'Trekking Backpack', 'A durable backpack for multi-day hikes.', 5, 99.99, 20, NOW()),
    (83, 'Cast Iron Pot', 'A sturdy cast iron pot for slow cooking.', 4, 59.99, 25, NOW()),
    (84, 'Adjustable Dumbbells', 'Dumbbells with adjustable weights.', 2, 129.99, 15, NOW()),
    (85, 'Camping Stove', 'A portable stove for camping trips.', 5, 39.99, 25, NOW()),
    (86, 'Puzzle Book', 'A book with challenging puzzles and riddles.', 3, 9.99, 90, NOW()),
    (87, 'Wireless Earbuds', 'Compact earbuds with high-quality sound.', 1, 79.99, 60, NOW()),
    (88, 'Foam Roller', 'A high-density foam roller for muscle recovery.', 2, 19.99, 80, NOW()),
    (89, 'Non-Stick Pan', 'A premium non-stick pan for easy cooking.', 4, 29.99, 40, NOW()),
    (90, 'Camping Sleeping Bag', 'A warm sleeping bag for camping.', 5, 79.99, 20, NOW()),
    (91, 'Kitchen Scale', 'A digital scale for accurate measurements.', 4, 14.99, 70, NOW()),
    (92, 'E-Book Reader', 'A sleek e-reader for book enthusiasts.', 3, 129.99, 15, NOW()),
    (93, 'Portable Power Station', 'A compact power station for camping.', 5, 199.99, 10, NOW()),
    (94, 'Juicer', 'A fast juicer for fresh drinks.', 4, 79.99, 25, NOW()),
    (95, 'Home Workout Guide', 'A guide with effective home workout routines.', 2, 14.99, 50, NOW()),
    (96, 'Laptop Sleeve', 'A protective sleeve for laptops.', 1, 24.99, 70, NOW()),
    (97, 'Insulated Mug', 'A double-walled insulated mug.', 4, 19.99, 30, NOW()),
    (98, 'Action Thriller', 'An action-packed thriller novel.', 3, 15.99, 80, NOW()),
    (99, 'Wireless Mouse', 'A lightweight and responsive mouse.', 1, 29.99, 100, NOW()),
    (100, 'Trekking Tent', 'A spacious trekking tent for 4 people.', 5, 129.99, 10, NOW());
